CREATE TABLE DEPT (ID NUMBER(6) NOT NULL, NAME VARCHAR(25), PRIMARY KEY (ID));
DESCRIBE dept;
INSERT INTO dept   SELECT  department_id, department_name  FROM    departments;
CREATE TABLE emp (ID NUMBER(7),LAST_NAME VARCHAR(25), FIRST_NAME VARCHAR(25), DEPT_ID NUMBER(7),FOREIGN KEY (DEPT_ID) REFERENCES DEPT(ID));
DESCRIBE emp;
CREATE TABLE EMPLOYEES2 AS ( SELECT EMPLOYEE_ID ID, FIRST_NAME , LAST_NAME, SALARY, DEPARTMENT_ID DEPT_ID FROM EMPLOYEES);
DESCRIBE EMPLOYEES2;
ALTER TABLE EMPLOYEES2 READ ONLY;
INSERT INTO EMPLOYEES2 VALUES (34,'Grant','Marcie',5678,10);
ALTER TABLE EMPLOYEES2 READ WRITE ;
INSERT INTO EMPLOYEES2 VALUES (34,'Grant','Marcie',5678,10);
DROP TABLE EMPLOYEES2;


















